{ config, pkgs, ... }:

{
  imports = [
    # /etc/nixos/hardware-configuration.nix # This will be generated by nixos-generate-config
  ];

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  networking.hostName = "axiom-os";
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timezone = "UTC";

  # I've added the dependencies from the original shell.nix here
  environment.systemPackages = with pkgs; [
    nim
    pkg-config
    webkitgtk
    gtk3
    git
    vim
    wget
    curl
  ];

  # Enable the NixOS config manager, optional.
  system.stateVersion = "24.05"; # Adjust to current NixOS version

  # User account configuration
  users.users.axiom = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" ];
    initialPassword = "axiom"; # Change this immediately after first boot
  };

  # Enable SSH
  services.openssh.enable = true;
}
